#!/usr/bin/env python3
"""Generate one MM2 conformance probe per PURE OP, grouped by type family.

WHY: MORK's conformance corpus covers 18 of upstream's 360 pure ops (5%). The recurring
width/arity/truncation defect class lives exactly there — `u8_leading_zeros` returns u32, so it
emits FOUR bytes, not one, and a port that returns u8 is silently wrong.

METHOD: emit the op's RAW result symbol (no `*_to_string` wrapper). The symbol's byte length IS
the result width, so this observes width directly instead of assuming a type. The conformance
runner compares `.expected` as BYTES, which is what makes that work.

Arguments are fed with `<T>_from_string`, chosen for BYTE WIDTH (upstream has no unsigned
from_string, so u8 is fed by i8_from_string etc. — `consume::<u8>` just reads the symbol bytes).
"""
import re, sys, os, collections

PURE_RS = os.path.expanduser("~/JuliaAGI/dev-zone/MORK/kernel/src/pure.rs")
OUT = sys.argv[1]

# type -> (feeder op, literal) chosen so the produced symbol has the RIGHT BYTE WIDTH.
FEED = {
    "u8":  ("i8_from_string",   "3"),   "i8":   ("i8_from_string",   "3"),
    "u16": ("i16_from_string",  "3"),   "i16":  ("i16_from_string",  "3"),
    "u32": ("i32_from_string",  "3"),   "i32":  ("i32_from_string",  "3"),
    "u64": ("i64_from_string",  "3"),   "i64":  ("i64_from_string",  "3"),
    "u128":("i128_from_string", "3"),   "i128": ("i128_from_string", "3"),
    "f32": ("f32_from_string",  "2.5"), "f64":  ("f64_from_string",  "2.5"),
}

def family(name):
    m = re.match(r'(u8|u16|u32|u64|u128|i8|i16|i32|i64|i128|f32|f64)_', name)
    if m: return m.group(1)
    m = re.search(r'_(u8|u16|u32|u64|u128|i8|i16|i32|i64|i128|f32|f64)$', name)
    return m.group(1) if m else "misc"

src = open(PURE_RS).read()
rows = []
for m in re.finditer(r'^op!\((num|str)\s+(\w+)\s+(\w+)\s*\(([^)]*)\)', src, re.M):
    kind, arity, name, params = m.groups()
    types = re.findall(r':\s*([A-Za-z0-9_]+)', params)
    rows.append((kind, arity, name, types))

groups = collections.defaultdict(list)
skipped = []
for kind, arity, name, types in rows:
    # nary's first macro arg is the INITIAL accumulator (an expr, not a param); its two typed
    # params are the accumulator and the element, so one feed type suffices.
    if arity == "nary":
        feed_types = [types[-1]] * 2 if types else []
    elif arity == "nulary":
        feed_types = []
    else:
        feed_types = types
    if any(t not in FEED for t in feed_types):
        skipped.append((name, arity, types))
        continue
    args = " ".join(f"({FEED[t][0]} {FEED[t][1]})" for t in feed_types)
    body = f"({name} {args})" if args else f"({name})"
    groups[family(name)].append(
        f"(exec 0 (, (n $x))\n  (O (pure ({name} $r) $r {body}))\n)")

os.makedirs(OUT, exist_ok=True)
total = 0
for fam, exprs in sorted(groups.items()):
    path = os.path.join(OUT, f"ops_{fam}.mm2")
    with open(path, "w") as f:
        f.write(f"; PURE OP coverage probe — {fam} family, {len(exprs)} ops.\n")
        f.write("; Emits each op's RAW result symbol: its BYTE LENGTH is the result width.\n")
        f.write("; Generated by scratchpad/gen_pure_probes.py from upstream kernel/src/pure.rs.\n")
        f.write("(n 1)\n")
        f.write("\n".join(exprs) + "\n")
    total += len(exprs)
    print(f"  ops_{fam}.mm2  {len(exprs)} ops")
print(f"\n{total} ops across {len(groups)} probe files")
if skipped:
    print(f"\nSKIPPED {len(skipped)} (unfeedable param types — inspect, do not assume benign):")
    for n, a, t in skipped[:15]:
        print(f"   {n:28s} {a:11s} {t}")
