#!/bin/bash
# mutation_trail.sh — BREAK THE UNDO TRAIL THREE WAYS AND RECORD WHICH SUITES NOTICE.
#
#   bash tools/mutation_trail.sh --check    # PRE-FLIGHT: anchors valid NOW. Seconds. ← the routine one
#   bash tools/mutation_trail.sh            # FULL MATRIX: 12 suite invocations on top of a 6-min
#                                           #   suite. NOT a per-commit check.
#
# 🔑 WHICH TO RUN WHEN. `--check` is cheap enough for every commit and catches the failure that
# actually bit us: an anchor moved by an edit to the very function under test. THE FULL MATRIX IS
# TRIGGERED, NOT SCHEDULED — run it when `match_candidate!` or `expr_unify_unwind!` CHANGES, because
# that is when the kill/survive rows can move. Wiring it into the gate would put 12 suite runs on a
# 4-core box behind every commit to buy a signal that only changes when those two functions do.
#
# ⚠️ DO NOT EDIT THIS FILE WHILE IT IS RUNNING. bash reads a script by FILE OFFSET as it executes, so
# inserting lines mid-run shifts everything after the read point. Measured 2026-08-21: two header
# edits during a matrix run produced ZERO rows and EXIT 0 — the sources restored correctly via the
# trap, but the run reported success having tested nothing. Hence the row-count assertion below.
#
# ─── WHY THIS EXISTS ────────────────────────────────────────────────────────────────────────────
# "1367/1367 green" says the same thing about a correct trail and a subtly wrong one until you have
# shown the tests can FAIL. The trail's oracle in `leapfrog_layer3d.jl` had never failed, and the
# cyclic-capture cases in `leapfrog_end_to_end.jl` were only trusted after a stub proved they catch
# a weakened binder. This applies the same standard to the trail itself.
# [[feedback_require_mutation_proof_from_agents]] · [[feedback_verify_the_oracle_runs]]
#
# ─── THE MUTANTS ────────────────────────────────────────────────────────────────────────────────
#   M1  `expr_unify_unwind!` unwinds to `mark + 1`   — the PRIMITIVE leaves one binding behind
#   M2  `match_candidate!` drops the FAILURE-path unwind — a failed solve leaves the map dirty
#   M3  `match_candidate!` drops the SUCCESS-path unwind — bindings leak to the next candidate
#
# ─── RESULT, 2026-08-21 (before the failure-path test existed) ──────────────────────────────────
#     mutant                        layer3d   trail   differential   end_to_end
#     M1 unwind to mark+1            killed   killed     killed        killed
#     M2 no unwind on FAILURE      SURVIVED SURVIVED   SURVIVED      SURVIVED     🔴
#     M3 no unwind on SUCCESS        killed SURVIVED     killed        killed
#
# ─── AND AFTER the failure-path test was added (re-run 2026-08-21, current expected matrix) ─────
#     M1                             killed   killed     killed        killed
#     M2                             KILLED SURVIVED   SURVIVED      SURVIVED
#     M3                             killed SURVIVED     killed        killed
# ⇒ M2/M3 surviving the files marked SURVIVED is EXPECTED and structural, not a regression: those
#   suites cannot observe a join-side unwind. Every mutant is killed by at least one suite.
#
# 🔴 M2 SURVIVED EVERYTHING — all four suites and the full 8153 — even though `expr_unify_trail.jl`'s
# own header calls that case "the one a happy-path test would miss and the one that corrupts
# silently". The reason is NOT weak assertions:
#     MEASURED over all 267 corpus programs — the failure branch is taken 4 TIMES, and 0 OF THOSE 4
#     had inserted before contradicting. The unwind M2 deletes has never had work to do here.
# ⚠️ A first diagnosis said "unreachable, candidate enumeration pre-filters by byte prefix". That was
# a MECHANISM STORY extrapolated from one zero on mm1, and the corpus figure refutes its
# "unreachable" half. The absent thing is the DIRTY case, not the branch.
# ⇒ `leapfrog_layer3d.jl` now constructs it — `(pair $x $x)` against `(pair a b)`, which binds
#   $x := a and then contradicts — and M2 IS KILLED (2 assertions). Re-run this script to confirm.
#
# ─── THE CORRECTION RECORD FOR THE FAILURE BRANCH — KEPT HERE, NOT IN THE FUNCTION BODY ─────────
# `match_candidate!`'s comment is four readings deep (current mechanism + three corrections) and that
# is the ceiling. A FIFTH correction goes HERE or into memory, and the source comment keeps only the
# current finding plus a pointer to this file. Wrong-and-why is worth keeping — each of these was
# written as a finding at the time — but not inside a hot function.
#   1. "unreachable — enumeration pre-filters by byte prefix"  ← mechanism story from ONE zero on mm1
#      REFUTED: the branch runs, in 2 programs.
#   2. "4 failures, 0 dirty across 267 programs"               ← wrong denominator AND wrong count:
#      the denominator is programs that ROUTE (263/267), and the 4 was 2 events double-counted by
#      `engine_work.jl`'s own warm-up pass. Volume is not the denominator anyway — 96% of candidates
#      are one program, and re-running one program's shapes does not sample new ones.
#   3. "a repeated-variable candidate inserts then fails, and the test constructs exactly that"
#      REFUTED: that shape is ABUNDANT (591 terms, 269 files) and produces ZERO binder failures —
#      the join settles coreference on the trie descent and hands the binder a consistent equation.
#   ⇒ CURRENT: both real failures are OCCURS violations, which fire BEFORE inserting, so 0 dirty is
#     STRUCTURAL. The layer3d case is a unit test of `match_candidate!`'s contract, NOT evidence of a
#     reachable join state.
#
# 🔑 M3 SURVIVED `expr_unify_trail.jl`, THE SUITE NAMED FOR THE TRAIL. That file tests the
# primitives; a join-level deletion is structurally outside it. Its header now says so, because the
# name otherwise implies coverage it does not have.
#
# ⚠️ RESTORES THE SOURCES ON EXIT, including on failure. It edits tracked files in place — check
# `git status` is clean before running, and confirm it is clean after.
set -u
cd "$(dirname "$0")/.."
BK=$(mktemp -d)
cp src/expr/ExprAlg.jl "$BK/" && cp src/kernel/Leapfrog.jl "$BK/"
restore() { cp "$BK/ExprAlg.jl" src/expr/ExprAlg.jl; cp "$BK/Leapfrog.jl" src/kernel/Leapfrog.jl; }
trap 'restore; rm -rf "$BK"' EXIT INT TERM

FILES="test/integration/leapfrog_layer3d.jl test/integration/expr_unify_trail.jl
       test/integration/leapfrog_differential.jl test/integration/leapfrog_end_to_end.jl"

apply() {
  restore
  case "$1" in
    M1) python3 -c "
import io;P='src/expr/ExprAlg.jl';s=io.open(P).read()
o='    while length(trail) > mark\n'
assert s.count(o)==1, 'M1 anchor moved'
io.open(P,'w').write(s.replace(o,'    while length(trail) > mark + 1\n',1))" ;;
    M2) python3 -c "
import io;P='src/kernel/Leapfrog.jl';s=io.open(P).read()
o='''        expr_unify_unwind!(bindings, trail, mark)
        return nothing'''
n='''        return nothing'''
assert s.count(o)==1, 'M2 anchor moved'
io.open(P,'w').write(s.replace(o,n))" ;;
    M3) python3 -c "
import io;P='src/kernel/Leapfrog.jl';s=io.open(P).read()
o='''    try
        with_bound_bytes!(c, bytes, () -> cont(bindings))
    finally
        expr_unify_unwind!(bindings, trail, mark)
    end'''
assert s.count(o)==1, 'M3 anchor moved'
io.open(P,'w').write(s.replace(o,'    with_bound_bytes!(c, bytes, () -> cont(bindings))'))" ;;
  esac
}

# 🔴 AN ANCHOR THAT NO LONGER MATCHES MUST BE A HARD FAILURE. A mutation script whose edit silently
# did nothing reports every mutant SURVIVED — the strongest possible false reassurance, and the same
# defect class as a sweep reporting success having measured nothing.
# ─── PRE-FLIGHT (`--check`): ARE THE ANCHORS STILL VALID *NOW*? ─────────────────────────────────
# The mutants match on source text living in the file they mutate, so ANY edit to `match_candidate!`
# or `expr_unify_unwind!` can move an anchor — including an edit made BECAUSE this script found
# something. The hard-failure guard below only reports that on the NEXT full run, and today that gap
# was hours. This mode applies each mutant, confirms the file actually CHANGED, restores, and
# confirms the tree is clean — seconds, no suites. Run it whenever those functions are touched.
#
# ⚠️ IT VALIDATES THAT A MUTANT *CHANGES* THE SOURCE, NOT THAT IT CHANGES IT *CORRECTLY*. An anchor
# that still matches but now sits in a different context yields a mutant that compiles and breaks
# something ADJACENT to the intended semantics — and the matrix would then report on a defect nobody
# chose. Cheap to note here, expensive to discover from a green row. When either function is
# restructured, re-read the three mutants against the new body, not just this check's ✓.
if [ "${1:-}" = "--check" ]; then
  rc=0
  for M in M1 M2 M3; do
    before=$(md5sum src/expr/ExprAlg.jl src/kernel/Leapfrog.jl)
    if ! apply $M 2>/dev/null; then echo "🔴 $M anchor MOVED — mutation results would be vacuous"; rc=1; continue; fi
    after=$(md5sum src/expr/ExprAlg.jl src/kernel/Leapfrog.jl)
    if [ "$before" = "$after" ]; then
      # 🔴 THE SILENT FAILURE THIS MODE EXISTS FOR: an edit that matched nothing leaves the source
      # untouched, every mutant "SURVIVES", and the matrix reads as maximal reassurance.
      echo "🔴 $M applied but source UNCHANGED — the mutant is a no-op"; rc=1
    else
      echo "✓ $M anchor valid (source changed)"
    fi
    restore
  done
  # ⚠️ COMPARE AGAINST THE BACKUP, NOT AGAINST HEAD. A first version used `git diff --quiet`, which
  # reports "RESTORE FAILED" whenever the tree holds legitimate uncommitted work — a false alarm on
  # the very check whose job is to be believed. The question is "did THIS script put the files back
  # as it found them", and only the backup answers it.
  if cmp -s "$BK/ExprAlg.jl" src/expr/ExprAlg.jl && cmp -s "$BK/Leapfrog.jl" src/kernel/Leapfrog.jl
  then echo "✓ sources restored byte-identical to pre-run state"
  else echo "🔴 RESTORE FAILED — sources left mutated"; rc=1; fi
  exit $rc
fi

fail=0
rows=0
printf "%-4s %-30s %s\n" "mut" "suite" "verdict"
for M in M1 M2 M3; do
  if ! apply $M; then echo "🔴 $M FAILED TO APPLY — anchor moved, results would be meaningless"; exit 1; fi
  for f in $FILES; do
    if ./tools/run_tests.sh "$f" >/dev/null 2>&1; then v="SURVIVED 🔴"; fail=1; else v="killed"; fi
    printf "%-4s %-30s %s\n" "$M" "$(basename "$f")" "$v"
    rows=$((rows + 1))
  done
done
echo
# 🔴 A ROW COUNT SHORT OF 3x4 MEANS THE RUN DID NOT HAPPEN — the same defect class as a sweep
# reporting zero rows as success, and this script hit it when its own source was edited mid-run.
if [ "$rows" -ne 12 ]; then
  echo "🔴 PRODUCED $rows/12 ROWS — the matrix measured NOTHING or died partway. Do not read the"
  echo "   rows above as a result; re-run with the file untouched."
  exit 1
fi
[ $fail -eq 0 ] && echo "✅ every mutant killed by at least one suite" \
                || echo "⚠️ a mutant survived a suite — expected for M2/M3 in the files named above; \
compare against the matrix in this header before treating it as a regression"
