# pure_handwritten_fns.jl — the TEN hand-written `extern "C"` fns of pure.rs (:748-908), plus the
# two arm families whose Julia stdlib equivalent is laxer than Rust's.
#
# WHY THIS FILE EXISTS. The 2026-07-30 sweep that fixed 52 drifted ops fixed the ops generated by the
# `op!` MACRO, by porting the arms instead of their expansion. It could not touch the ten functions
# upstream writes out BY HAND — `encode_hex`, `decode_hex`, `encode_base64url`, `decode_base64url`,
# `hash_expr`, `reverse_symbol`, `collapse_symbol`, `explode_symbol`, `ifnz`, `tuple` — because those
# have no arm to port. They were the last unexamined surface in the file, and four of them diverged.
#
# GROUND TRUTH: every expectation below was produced by running the corresponding MM2 program through
# the upstream release binary (`mork run probe.mm2 probe.raw`, output pinned to a FILE — stdout
# replaces invalid UTF-8 and most of these ops emit high bytes).
#
# 🔴 THE SEVERE ONE. `collapse_symbol` had no 63-byte cap. The oversized result is not rejected by the
# op, it is rejected by the Expr layer when WRITTEN, so the throw escaped the pure sink's per-atom
# error handling as a TaskFailedException and ABORTED THE WHOLE EXEC RUN — one bad atom took down all
# nine probes in its file, where upstream skips that atom and continues. A permissive op that defers
# its validation to a lower layer converts "skip one row" into "lose the program".
# ⚠️ WHAT THIS FILE ACTUALLY MEASURES, established 2026-07-31 by deleting the entries and watching
# it go red with "Unknown pure op". `_hw` calls `MORK.pure_apply`, which dispatches through
# `PURE_OPS`. For these ten names `pure_register!` installs the NATIVE `(ExprSource, ExprSink)`
# function instead (Pure.jl:1385), so the bodies exercised below are NOT the code the sinks call.
#
# The natives are covered end to end by the 2792-point pure-op differential and the conformance
# corpus, both of which run real MM2 through the registered scope. The gap is unit coverage at this
# layer, and closing it means routing `pure_apply` through `scope_eval!` — which changes its return
# from a raw payload to an encoded expression and touches every assertion in five files.
#
# So the expectations below remain valuable — they are upstream binary output, and they pin the
# byte-level semantics — but do not read a green run here as proof that the registered natives work.
using MORK, Test

_hw_sym(s) = vcat(UInt8[MORK.item_byte(MORK.ExprSymbol(UInt8(length(s))))],
                  Vector{UInt8}(codeunits(String(s))))
_hw_expr(items...) = vcat(UInt8[MORK.item_byte(MORK.ExprArity(UInt8(length(items))))], items...)
_hw(name, args...) = MORK.pure_apply(name, Vector{UInt8}[args...])
_hw_str(name, args...) = String(_hw(name, args...))

@testset "pure.rs hand-written extern fns" begin
    @testset "collapse_symbol — all three upstream Err paths" begin
        # (collapse_symbol ('(a b c))) => abc   [binary: (q_ok abc)]
        @test _hw_str("collapse_symbol", _hw_expr(_hw_sym("a"), _hw_sym("b"), _hw_sym("c"))) == "abc"

        # A non-Symbol element is `Err("can only concat symbols in collapse")`, NOT a partial result.
        # (collapse_symbol ('(a (b c)))) => no atom.  We used to `break` and return "a".
        @test_throws Exception _hw("collapse_symbol",
                                   _hw_expr(_hw_sym("a"), _hw_expr(_hw_sym("b"), _hw_sym("c"))))

        # A non-expression argument is `Err("argument should be an expression")`. Upstream prints a
        # stray `si [102, 111, 111]` and returns Err; we used to fall through to `reduce(vcat, a)` and
        # return "foo".  (collapse_symbol foo) => no atom.
        @test_throws Exception _hw("collapse_symbol", _hw_sym("foo"))
        @test_throws Exception _hw("collapse_symbol", UInt8[])

        # The cap is `i + symbol.len() >= 64`, so 63 bytes total is the MAXIMUM and 64 is rejected.
        # Pinned on both sides of the boundary: 32+27=59 emitted a 59-byte symbol (q_63), 32+32=64
        # emitted nothing (q_over).
        a32, b31, b32 = "a"^32, "b"^31, "b"^32
        @test length(_hw("collapse_symbol", _hw_expr(_hw_sym(a32), _hw_sym(b31)))) == 63
        @test _hw_str("collapse_symbol", _hw_expr(_hw_sym(a32), _hw_sym("b"^27))) == a32 * "b"^27
        @test_throws Exception _hw("collapse_symbol", _hw_expr(_hw_sym(a32), _hw_sym(b32)))
    end

    @testset "explode_symbol / reverse_symbol / tuple" begin
        # (explode_symbol abc) => (a b c)
        @test _hw("explode_symbol", Vector{UInt8}("abc")) ==
              _hw_expr(_hw_sym("a"), _hw_sym("b"), _hw_sym("c"))
        # Round trip, which is upstream's own test shape (main.rs:1130).
        @test _hw_str("collapse_symbol", _hw("explode_symbol", Vector{UInt8}("abc"))) == "abc"
        # A symbol is parser-capped at 63 bytes, so the 6-bit Arity tag here can never overflow —
        # upstream truncates a 64- and 65-byte literal to 63 at PARSE time (measured: 62/63/64/65
        # bytes in gave 62/63/63/63 elements out). No guard is needed; this pins the reachable edge.
        @test length(_hw("explode_symbol", Vector{UInt8}("a"^63))) == 1 + 2 * 63

        @test _hw_str("reverse_symbol", Vector{UInt8}("abc")) == "cba"

        # tuple has NO arity check (upstream writes Arity(items) then splices each element's span).
        # (tuple) => ()   (tuple a) => (a)
        @test _hw("tuple") == UInt8[MORK.item_byte(MORK.ExprArity(UInt8(0)))]
        @test _hw("tuple", _hw_sym("a")) == _hw_expr(_hw_sym("a"))
        # Each element is spliced VERBATIM, so a nested expression stays nested.
        @test _hw("tuple", _hw_sym("a"), _hw_expr(_hw_sym("b"), _hw_sym("c"))) ==
              _hw_expr(_hw_sym("a"), _hw_expr(_hw_sym("b"), _hw_sym("c")))
    end

    @testset "hex / base64url" begin
        @test _hw_str("encode_hex", Vector{UInt8}("aa")) == "6161"
        @test _hw_str("decode_hex", Vector{UInt8}("6161")) == "aa"
        # URL-safe, UNPADDED both directions (upstream uses URL_SAFE_NO_PAD).
        @test _hw_str("encode_base64url", Vector{UInt8}("abc")) == "YWJj"
        @test _hw_str("decode_base64url", Vector{UInt8}("YWJj")) == "abc"
        # ⚠️ UPSTREAM BUG, deliberately NOT reproduced. `encode_hex` writes into a `[0u8; 64]` at
        # `buf[..2*symbol.len()]` (pure.rs:755), so a 32-byte input yields a 64-byte symbol that
        # violates the Rule of 64 (the binary emitted a corrupt `$a`), and a 33-byte input PANICS:
        #   thread 'main' panicked at kernel/src/pure.rs:755:42:
        #   range end index 66 out of range for slice of length 64
        # A panic in `extern "C"` is a non-unwinding ABORT — the process dies and no output file is
        # written at all. Same class as the `mod`-by-zero / inverted-`clamp` aborts: we must never
        # abort mid-saturation, so we keep going. Recorded so a "match upstream" sweep cannot import
        # a process abort. Safe upstream range is inputs <= 31 bytes.
        @test length(_hw("encode_hex", Vector{UInt8}("a"^31))) == 62
    end

    @testset "from_string is STRICT — Rust's grammar is [+-]?[0-9]+" begin
        # Julia's bare `parse` accepts these; Rust's `str::parse` does not, so we were emitting atoms
        # upstream never produces. Measured: `0x10` and `0b101` yielded 16 and 5 here and NO atom
        # upstream; `1_000` and `5abc` already agreed (both reject).
        for bad in ("0x10", "0b101", "0o17", "1_000", "5abc", " 5", "5 ", "", "+", "-", "1e3")
            @test_throws Exception _hw("i64_from_string", Vector{UInt8}(bad))
        end
        @test _hw("i64_from_string", Vector{UInt8}("+5")) == MORK._be_bytes(Int64(5))
        @test _hw("i64_from_string", Vector{UInt8}("-5")) == MORK._be_bytes(Int64(-5))
        @test _hw("i64_from_string", Vector{UInt8}("5")) == MORK._be_bytes(Int64(5))
        @test _hw("i8_from_string", Vector{UInt8}("127")) == MORK._be_bytes(Int8(127))
        @test_throws Exception _hw("i8_from_string", Vector{UInt8}("128"))   # overflow: Err both sides
        @test _hw("i128_from_string", Vector{UInt8}("-170141183460469231731687303715884105728")) ==
              MORK._be_bytes(typemin(Int128))

        # FLOAT parsing is Rust-compatible as-is and is NOT narrowed by the guard above: the binary
        # accepts `NaN`, `inf` and the long form `infinity`, and so does Julia.
        @test _hw("f64_from_string", Vector{UInt8}("infinity")) == MORK._be_bytes(Inf)
        @test _hw("f64_from_string", Vector{UInt8}("inf")) == MORK._be_bytes(Inf)
        @test _hw("f64_from_string", Vector{UInt8}("NaN")) == MORK._be_bytes(NaN)
        @test _hw("f64_from_string", Vector{UInt8}("1e3")) == MORK._be_bytes(1000.0)
    end

    @testset "powi is a MULTIPLY CHAIN, not libm pow" begin
        # `f64::powi` lowers to llvm.powi / __powidf2 (binary exponentiation by repeated
        # multiplication). Julia's `^` calls libm `pow`, which is MORE accurate and therefore
        # DIVERGENT. Bytes pinned from the binary:
        #   (powi_f64 1.1 10) = 40 04 bf fc 0c 03 02 3d   (ours was …3e — 1 ULP high)
        #   (powi_f64 0.1 3)  = 3f 50 62 4d d2 f1 a9 fd
        #   (powi_f32 1.1 10) = 40 25 ff e3
        @test _hw("powi_f64", MORK._be_bytes(1.1), MORK._be_bytes(Int32(10))) ==
              UInt8[0x40, 0x04, 0xbf, 0xfc, 0x0c, 0x03, 0x02, 0x3d]
        @test _hw("powi_f64", MORK._be_bytes(0.1), MORK._be_bytes(Int32(3))) ==
              UInt8[0x3f, 0x50, 0x62, 0x4d, 0xd2, 0xf1, 0xa9, 0xfd]
        @test _hw("powi_f32", MORK._be_bytes(1.1f0), MORK._be_bytes(Int32(10))) ==
              UInt8[0x40, 0x25, 0xff, 0xe3]
        # Shape properties of the chain: n=0 is 1.0 for every base, and a negative exponent is the
        # reciprocal of the positive one (`recip` in __powidf2), never a DomainError.
        @test _hw("powi_f64", MORK._be_bytes(7.5), MORK._be_bytes(Int32(0))) == MORK._be_bytes(1.0)
        @test _hw("powi_f64", MORK._be_bytes(2.0), MORK._be_bytes(Int32(-2))) == MORK._be_bytes(0.25)
        # `b /= 2` truncates toward zero and `b & 1` is 1 for odd negatives, so typemin needs no
        # special case (an `abs`-based formulation would overflow here).
        @test _hw("powi_f64", MORK._be_bytes(1.0), MORK._be_bytes(typemin(Int32))) ==
              MORK._be_bytes(1.0)
    end
end
